import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google"; //1
import "./globals.css";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const notoSerifBengali = Noto_Serif_Bengali({
  //1
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className}  h-full antialiased`} //1
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <Marquee/>
        <main className="max-w-7xl mx-auto">
        {children}
        </main>
        <Footer/>
        <Toaster/>
      </body>
    </html>
  );
}
